Sprint №14
AnatolyB0brov/java-shareit pull request #1
Opened 2024-11-13 18:11 UTC by AnatolyB0brov

2024-11-14 17:38 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/controller/ItemController.java
> +    @GetMapping
`"X-Sharer-User-Id"` лучше сделать строковой константой проекта, она будет встречаться еще не один раз

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/ItemMapper.java
> +public class ItemMapper {
Это класс-помощник или `@UtilityClass` лучше организовать его одним из двух способов, как написано в статье:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/UserMapper.java
> +public class UserMapper {
Аналогично про это уже писал

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/UserServiceImpl.java
> +        if (userRepository.findAll().stream().anyMatch(user -> user.getEmail().equals(userDto.getEmail()))) {
Это работает за `O(n)`, где `n` -- количество пользователей, при росте `n` этот метод может начать работать, крайне медленно, при использовании коллекции `Set` и правильной организации хранения данных этот метод можно реализовать за `O(1)`

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/ItemServiceImpl.java
> +        } else {
Можно инвертировать условный оператор и избавиться от ветки `else`

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/repository/impl/UserRepositoryImpl.java
> +    private static int userId = 0;
Это поле не стоит делать статическим

2024-11-14 17:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/repository/impl/ItemRepositoryImpl.java
> +    private static int itemId = 0;
Это поле не стоит делать статическим

2024-11-18 09:11 UTC, AnatolyB0brov commented on src/main/java/ru/practicum/shareit/service/impl/UserServiceImpl.java
> +        if (userRepository.findAll().stream().anyMatch(user -> user.getEmail().equals(userDto.getEmail()))) {
С этим замечанием не согласен, т.к. тут есть некое нарушение причинно-следственной связи. `n` не успеет достигнуть такой величины, когда этот метод начнет выполняться медленно, т.к. ДО этого момента я получу что-то вроде Out of memory из-за достижения коллекции, которая хранит юзеров, огромных размеров. Эта причина, но не только она, заставит меня хранить коллекцию юзеров в БД. А там я сделаю какой-нибудь индекс по полю email и буду одним запросом проверять, есть ли пользователь с таким мылом в БД или нет. Изощряться из-за этого сейчас и переделывать хранение в памяти каким-то более сложным образом, я не вижу смысла. Хранение в памяти само по себе- странное требование, на которое мы все закрываем глаза, т.к. сейчас идет обучение. Предлагаю таким же образом закрыть глаза на потенциальное уменьшение скорости этого метода

2024-11-18 09:17 UTC, AnatolyB0brov commented
Спасибо большое за ревью. Там в одном моменте я попытался поспорить, остальные замечания исправил

2024-11-27 07:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/UserServiceImpl.java
> +        if (userRepository.findAll().stream().anyMatch(user -> user.getEmail().equals(userDto.getEmail()))) {
> `n` не успеет достигнуть такой величины, когда этот метод начнет выполняться медленно

Тут надо понимать две вещи: что такое выполняться медленно, что такое не успеет достигнуть.

При стандартных настройках JVM действительно может возникнуть такая ошибка `java.lang.OutOfMemoryError: Java heap space`. Но надо понимать, что `heap space` можно увеличить, если это позволяют ресурсы компьютера, где запускается программа. JVM при запуске принимает следующие аргументы: `-Xmx3072M -Xms3072M` позволяющие изменять `heap size`. Таким образом нет никаких технических ограничений (кроме существующего у тебя размера диска) на размер данной коллекции, и если у нас есть большой диск для размещения СУБД, то нет никакой технической сложности развернуть там приложение для которого данная коллекция будет достигать огромных размеров. 

Теперь вопрос насколько медленно может выполняться эта проверка. Даже при `heap size` по умолчанию она может выполняться до 400 мс (в зависимости от машины, на которой запущена -- можно поэкспериментировать). Возникает вопрос, много это или мало? Если у нас один пользователь приложения, то это терпимо, а если их тысячи или сотни тысяч? И пики нагрузки у нас массовые (например, если бы у нас была система продажи билетов на концерт Тейлор Свифт, они разлетаются в первые минуты с анонса продаж), следовательно надо понимать, что понятия "не успеет достигнуть" и "выполняться медленно" они сильно зависят от нашей трактовки.

Сейчас требовать исправления я не буду, но на самом деле хранение в памяти -- не такая уж глупая идея. Поскольку в памяти мы имеем более быстрый доступ данным, а в СУБД -- консистентный. И скорость отдачи во многих приложениях обусловлена наличием кэшей, которые работают как раз с памятью (хоть они и устроены немного умнее, чем просто `Map`)

2024-11-27 07:38 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-11-27 13:41 UTC, AnatolyB0brov commented on src/main/java/ru/practicum/shareit/service/impl/UserServiceImpl.java
> +        if (userRepository.findAll().stream().anyMatch(user -> user.getEmail().equals(userDto.getEmail()))) {
Спасибо! Я все понял

2024-11-28 09:52 UTC, merged