Sprint №15.
AnatolyB0brov/java-shareit pull request #2
Opened 2024-11-28 10:06 UTC by AnatolyB0brov

2024-11-29 06:29 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-11-29 06:29 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text VARCHAR(1000) NOT NULL,
Не стоит называть поле аналогично типу данных в стандарте, либо стоит использовать экранирование при помощи `""`

2024-11-29 06:29 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Все внешние ключи, используемые в таблицах ниже не помечены, как `not null`?
они действительно могут быть не заполнены? кажется, что некоторые из них точно можно пометить, как `not null`

2024-11-29 06:29 UTC, LexLippi commented on src/main/resources/schema.sql
> +    status varchar(25) NOT NULL
Если `status` это перечисление, то можно добавить ограничение на значение данной колонки при помощи `check (status in (...))`, где вместо многоточия перечислены допустимые значения перечисления

2024-11-29 06:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/ItemServiceImpl.java
> +        } else {
Можно инвертировать условный оператор и избавиться от ветки `else`, что позволит сократить вложенность кода

2024-11-29 06:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/BookingServiceImpl.java
> +        bookings = switch (bookingState) {
Зачем объявлять `bookings` заранее, если можно сделать это, не отрывая от инициализации

2024-11-29 06:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/impl/BookingServiceImpl.java
> +        bookings = switch (bookingState) {
Аналогичный вопрос

2024-11-29 06:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/CommentMapper.java
> +public final class CommentMapper {
Этот класс стоит организовать, как класс-помощник или как `UtilityClass`:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-11-29 06:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/BookingMapper.java
> +public final class BookingMapper {
Аналогично про все мапперы

2024-11-29 13:47 UTC, AnatolyB0brov commented on src/main/java/ru/practicum/shareit/mapper/CommentMapper.java
> +public final class CommentMapper {
Так я их так и организовал, как в статье. Класс отмечен, как final, а методы статические. Если нужно что-то ещё, то напиши, пожалуйста, что именно

2024-11-29 13:47 UTC, AnatolyB0brov commented on src/main/java/ru/practicum/shareit/mapper/BookingMapper.java
> +public final class BookingMapper {
Так я их так и организовал, как в статье. Класс отмечен, как final, а методы статические. Если нужно что-то ещё, то напиши, пожалуйста, что именно.

2024-12-02 07:24 UTC, AnatolyB0brov commented
Привет. Спасибо за ревью. Остался непонятным момент по поводу утилитарных классов.

2024-12-03 17:00 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/BookingMapper.java
> +public final class BookingMapper {
Привет, не хватает приватного конструктора без аргументов, но работу я приму, давай устраним это до следующего спринта!

2024-12-03 17:00 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-12-03 18:18 UTC, AnatolyB0brov commented on src/main/java/ru/practicum/shareit/mapper/BookingMapper.java
> +public final class BookingMapper {
Понял, спасибо!

2024-12-03 18:19 UTC, merged